export const placeholderArticles = [
    "Storia di Roma",
    "Rivoluzione francese",
    "Teoria della relatività",
    "Fotosintesi clorofilliana",
    "Motore a scoppio",
    "Intelligenza artificiale",
    "Rinascimento",
    "Divina Commedia",
    "Pop art",
    "Tyrannosaurus rex",
    "Acido desossiribonucleico",
    "Gatto domestico",
    "Monte Bianco",
    "Fossa delle Marianne",
    "Foresta Amazzonica",
    "Pianoforte",
    "Caffettiera",
    "Esistenzialismo",
    "Globalizzazione",
    "Mitologia greca",
    "Pizza",
    "Cioccolato",
    "Sistema solare",
    "Rivoluzione industriale",
    "Seconda guerra mondiale",
    "Meccanica quantistica",
    "Teoria dell'evoluzione",
    "Elettrone",
    "Tavola periodica degli elementi",
    "Buco nero",
    "Riscaldamento globale",
    "Internet",
    "Microscopio",
    "Telescopio spaziale",
    "Vaccino",
    "Penicillina",
    "Impero romano",
    "Antica Grecia",
    "Antico Egitto",
    "Guerra fredda",
    "Magna Charta",
    "Costituzione della Repubblica Italiana",
    "Diritto romano",
    "Democrazia",
    "Capitalismo",
    "Socialismo",
    "Buddismo",
    "Cristianesimo",
    "Islam",
    "Induismo",
    "Lingua esperanto",
    "Alfabeto latino",
    "Stele di Rosetta",
    "Psicologia",
    "Psicoanalisi",
    "Filosofia della scienza",
    "Trigonometria",
    "Numero pi greco",
    "Sezione aurea",
    "Logica matematica",
    "Crittografia",
    "Blockchain",
    "Energia nucleare",
    "Energia solare",
    "Effetto serra",
    "Tettonica delle placche",
    "Vulcano",
    "Terremoto",
    "Atmosfera terrestre",
    "Barriera corallina",
    "Dinamica dei fluidi",
    "Termodinamica",
    "Fotografia",
    "Cinematografia",
    "Musica classica",
    "Jazz",
    "Rock and roll",
    "Architettura gotica",
    "Bauhaus",
    "Colosseo",
    "Partenone",
    "Muraglia cinese",
    "Piramidi di Giza",
    "Taj Mahal",
    "Stampa a caratteri mobili",
    "Ruota",
    "Carta",
    "Bussola",
    "Polvere da sparo",
    "Oro",
    "Argento",
    "Ferro",
    "Acqua",
    "Carbonio",
    "Ossigeno",
    "Ecosistema",
    "Biodiversità",
    "Selezione naturale",
    "Genetica",
    "Nanotecnologia",
];
